# List of source files
SRC += $(SRC_DIR)/background.vhd
SRC += $(SRC_DIR)/ball_move.vhd
SRC += $(SRC_DIR)/computer_move.vhd
SRC += $(SRC_DIR)/player_move.vhd
SRC += $(SRC_DIR)/pong.vhd
SRC += $(SRC_DIR)/sprite_pkg.vhd

# List of test specific simulation files
SRC += tb_pong.vhd

# Top level entity
DUT = pong

# Test duration
STOP_TIME = 1us

# Don't stop on errors
#ASSERT_LEVEL = none

include ../Makefile.inc

